name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd climbing-app
          npm i
          cd frontend
          npm i
          npm run build
          cd ..
          pm2 stop climbing-app
          pm2 start --name climbing-app backend/index.js
          
